### PR TITLE
Development

### PR DESCRIPTION
**Pull request by nikasulo**

### CODE REVIEW

**Comment by bellom** [comment]
currently reviewing this project

**Review by bellom — CHANGES_REQUESTED** [review]
Hi Team, 
Well done, all test case working fine but **you need to add linter to the project.**
Always read the pathwright instructions before starting the project to avoid you sending another code review, according to the pathwright you are to use Git Flow not GitHub Flow.
Short Explanation Hint: 
`GitHub Flow`: Pull Requests is raise from `feature branches to the master`.
`Git Flow`: Pull Requests is raise from `feature branches to the development`.

Kindly re-submit for review after making the changes :slightly_smiling_face: Thumps -up await you

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Hello @evaveskova,

Good improvement adding the linter to your project. However, the checks need to pass to get a thumb up. :slightly_smiling_face: 

image
Click and check the details of the failing check and make the necessary corrections, shouldn't take you much time to fix. :grin:

When you're done, request for one last re-review. :sunglasses:

**P.S.**

Please ensure to use the `git-flow` guideline in your future projects. Check [this](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) for more details.

**Comment by maelfosso** [comment]
# Good job :+1: 

You can merge and submit the project completion form.
Good luck with the next project

**Pull request merged**
